# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Global/Global.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Global || ORIG_REF_NAME==Global} -quiet] -quiet

# IP: bd/Global/ip/Global_processing_system7_0_0/Global_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Global_processing_system7_0_0 || ORIG_REF_NAME==Global_processing_system7_0_0} -quiet] -quiet

# IP: bd/Global/ip/Global_Linear_Trasnformation_0_0/Global_Linear_Trasnformation_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Global_Linear_Trasnformation_0_0 || ORIG_REF_NAME==Global_Linear_Trasnformation_0_0} -quiet] -quiet

# IP: bd/Global/ip/Global_ps7_0_axi_periph_0/Global_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Global_ps7_0_axi_periph_0 || ORIG_REF_NAME==Global_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Global_rst_ps7_0_50M_0 || ORIG_REF_NAME==Global_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Global/ip/Global_auto_pc_0/Global_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Global_auto_pc_0 || ORIG_REF_NAME==Global_auto_pc_0} -quiet] -quiet

# XDC: bd/Global/Global_ooc.xdc
