# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0.xci
# IP: The module: 'Global_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Global_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Global_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Global_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0.xci
# IP: The module: 'Global_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Global_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Global_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_rst_ps7_0_50M_0/Global_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Global_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
