# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_processing_system7_0_0/Global_processing_system7_0_0.xci
# IP: The module: 'Global_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_processing_system7_0_0/Global_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Global_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_processing_system7_0_0/Global_processing_system7_0_0.xci
# IP: The module: 'Global_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Testing_on_card/Testing_on_ZEDBOARD.srcs/sources_1/bd/Global/ip/Global_processing_system7_0_0/Global_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Global_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
